### PR TITLE
Use RabbitMQ with Testcontainers for testing.

### PR DESCRIPTION
**Pull request by daharon**
Updated the test to use [ZIO-Testcontainers](https://github.com/sideeffffect/zio-testcontainers) instead of relying on a separately running instance of RabbitMQ.

### CODE REVIEW

**Comment by daharon** [comment]
I was trying to get the CircleCI tests to pass, but the problems there are more involved.
For a different PR...

**Comment by daharon** [comment]
I added Github Actions for linting and testing as a replacement for CircleCI, if that's alright.
It is just easier when using _Testcontainers_ and it runs faster.

**Comment by svroonland** [comment]
Thanks! I'm happy to accept the TestContainer changes, but I want to stick to CircleCI for now as I'm also using that in other projects and maintaining two build systems would be too much trouble.

**Comment by daharon** [comment]
Ok, I will try again to get it working in CircleCI.

**Comment by svroonland** [comment]
What's the problem you run into with circleci? Maybe I can help

**Comment by Adriani277** [comment]
Done in https://github.com/zio/zio-amqp/pull/362
Please re-open if that is not the case

**Pull request closed without merging**
